Fix fnmatch adjacent nested curly braces
editorconfig/editorconfig-core-py pull request #33
Opened 2020-11-28 20:57 UTC by kevinoid

If an fnmatch expression had adjacent nested curly braces, the braces would be treated as literals.  For example:

```py
translate('{a,{b,c}}') == '(?s)\\{a\\,\\{b\\,c\\}\\}\\Z'
translate('{{a,b},c}') == '(?s)\\{\\{a\\,b\\}\\,c\\}\\Z'
```

They should be translated as:

```py
translate('{a,{b,c}}') == '(?s)(?:a|(?:b|c))\\Z'
translate('{{a,b},c}') == '(?s)(?:(?:a|b)|c)\\Z'
```

This can occur when matching a mix of file names and extensions.  For example, I encountered the issue for `{CMakeLists.txt,*.{c,cmake,sh}}`.

The issue occurs because `LEFT_BRACE` and `RIGHT_BRACE` include the preceding character in the match, which causes the match to skip the second adjacent curly brace, which causes the match count to differ.  To avoid this, use a zero-width assertion (negative look-behind in this case).

Note: This makes adjacent nested curly braces behave the same as editorconfig-core-c.

Thanks for considering,
Kevin

2020-11-29 08:40 UTC, greut commented
Very interesting, did you see if such tests exist in [core-test](https://github.com/editorconfig/editorconfig-core-test) ?

2020-11-29 15:00 UTC, kevinoid commented
Thanks for the pointer to core-test @greut.  This case does not appear to be covered by the current tests.  I've submitted editorconfig/editorconfig-core-test#44 to cover it.

2020-12-06 04:55 UTC, xuhdev approved these changes
LGTM! Thanks for the catch!

2020-12-06 05:02 UTC, xuhdev requested changes
I tried to run this change against the latest tests, seems like it is breaking a couple of tests: https://travis-ci.org/github/editorconfig/editorconfig-core-py/jobs/747898482

Could you bump the test submodule in your PR so we can track the CI status directly in this PR?

2020-12-06 14:44 UTC, kevinoid commented
Thanks @xuhdev.  I don't think the test failures are due to this PR.  I cherry-picked fb7b696 from #34 onto `master`  and got [the same test failures](https://travis-ci.org/github/kevinoid/editorconfig-core-py/jobs/747939158).  It looks like they are fixed by commits in #32.

A suggestion: Drop 2ca227a (The most recent commit, which includes the braces tests for this issue.) from #32 and merge into `master`.  Once merged, I'll rebase this PR onto `master` and cherry-pick 2ca227a.  Would that be acceptable?

2020-12-07 06:19 UTC, xuhdev commented
@kevinoid Certainly. Let's do #32 first

2020-12-07 07:32 UTC, xuhdev commented
#32 has been merged. Could you rebase and bump the test submodule?

2020-12-07 14:59 UTC, kevinoid commented
Sure thing.  Thanks @xuhdev!

I've rebased onto `master` and cherry-picked 2ca227a which bumps tests to master.  Tests pass on my machine and CI is running now.  Should be green shortly.

2020-12-07 19:21 UTC, xuhdev approved these changes
LGTM. Thanks for the contribution!

2020-12-07 19:22 UTC, merged

2020-12-07 19:43 UTC, kevinoid commented
My pleasure.  Thanks for reviewing and merging it @xuhdev.